# Generated by Django 4.1.9 on 2023-09-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DM',
        ),
    ]
