version: '3.8'
volumes:
  data:

services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", '0.0.0.0:8000']
    ports:
      - 8000:8000
    volumes:
      - .:/app
  redis:
    image: redis:latest
    volumes:
      - data:/data
    ports:
      - 6379:6379
