# Generated by Django 4.1.9 on 2023-09-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
